In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
from scipy.stats import pearsonr
from sklearn.decomposition import PCA
import statsmodels.formula.api as mf
import seaborn as sns

def plot_circle_corr(x,y):
    
        fig,ax=plt.subplots()
        ax.axhline(y=0,color='k')
        ax.axvline(x=0,color='k')
        theta=np.linspace(0,2*np.pi,100)
        x1=np.cos(theta)
        x2=np.sin(theta)
        ax.plot(x1,x2)
        G1=x.to_numpy().astype(float)
        G2=y.to_numpy().astype(float)
        ax.scatter(G1,G2,s=150,color="k")
        for i in range(len(G1)):
            text.append(x.index[i])
            ax.annotate(text[i],(G1[i],G2[i]),fontsize=13,color='b')

        v=G1.tolist()
        w=G2.tolist()
        for i in range(len(G1)):
            array = np.array([[0, 0, v[i], w[i]], [0, 0, v[i],w[i]]])
            X, Y, V, W = zip(*array)
            ax.quiver(X, Y, V, W, angles='xy', scale_units='xy',color=['r','r'],scale=1)


        ax.grid(linestyle='--')
        ax.show()
        #fin de circle
        return ax.close()
def plot_corrdonne(x,y):
        fig,ax=plt.subplots()
        ax.axhline(y=0,color='k')
        ax.axvline(x=0,color='k')
        ax.grid(True)
        F1_=x.to_numpy()
        F2_=y.to_numpy()
        ax.scatter(F1_,F2_,s=150,color="k")
        for i in range(len(F1)):
            text.append(y.index[i])
            ax.annotate(text[i],(F1_[i],F2_[i]),fontsize=13)
        ax.plot()
        return plt.close()



inertie_relative=[]
indexe=[]

#matrix correlation 


#from sklearn.preprocessing import StandarScaler
dat=pd.read_csv("prb.csv")
for i in dat["Unnamed: 0"]:
    indexe.append(i)
dat=dat.drop("Unnamed: 0",axis=1)
print(dat.corr())
text=[]
x=[]
G1=[]
G2=[]
n=4
m=9
matrix=dat.to_numpy().astype(float)
x=matrix.mean(axis=0)
y=matrix.std(axis=0)
print(y)
for i in range(m):
    for j in range(n):
        matrix[i][j]=(matrix[i][j]-x[j])/y[j]
tran=(1/m)*np.dot(matrix.T,matrix)
data=pd.DataFrame(matrix,index=indexe,columns=['prv',"add","vitess","logistique de transport"])
print("----------MATRIX OF COR---------")
R=pd.DataFrame(tran,index=data.columns,columns=data.columns)
R=R.to_numpy().astype(float)
p=np.linalg.eigvals(R)
inertie_absolue=[p[0],p[1],p[0]+p[1]]
for i in range(len(inertie_absolue)):
    inertie_relative.append(inertie_absolue[i]/n)
#print(inertie_absolue,inertie_relative)
h=np.linalg.eig(R)
b=h[1:2]
def colum(mat,i):
    return [row[i].T for row in mat]
u1=np.array(colum(b,0))
u2=np.array(colum(b,1))
F1=pd.DataFrame(np.dot(matrix,u1.T),index=data.index)
F2=pd.DataFrame(np.dot(matrix,u2.T),index=data.index)
print("\n",matrix)
print(F2[0])
for i in range(4):
    coef_cor,pvalue=pearsonr(matrix[:,i],F1[0])
    G1.append(coef_cor)
    coef_cor,pvalue=pearsonr(matrix[:,i],F2[0])
    G2.append(coef_cor)
G1=pd.DataFrame(G1,index=data.columns)
G2=pd.DataFrame(G2,index=data.columns)
print("\n",G1)
print(G2)

data.corr().style.background_gradient(cmap="Blues")



             Prévision       ADD   Logistique   Transport
Prévision      1.000000  0.987493     0.232100   0.496744
ADD            0.987493  1.000000     0.376195   0.617943
Logistique     0.232100  0.376195     1.000000   0.945431
Transport      0.496744  0.617943     0.945431   1.000000
[3.37474279 2.99794168 3.43996124 2.85557717]
----------MATRIX OF COR---------

 [[-1.08650256 -1.2971863  -1.50195491 -1.61477377]
 [-0.4938648  -0.63006192 -0.62985206 -0.73929401]
 [-1.08650256 -0.96362411  0.24225079 -0.21400616]
 [ 1.43220792  1.53809233  1.55040507  1.7120493 ]
 [ 1.28404848  1.37131124  0.53295174  0.83656954]
 [ 0.39509184  0.20384356 -1.35660443 -1.08948592]
 [-1.234662   -0.96362411  1.11435364  0.48637764]
 [ 0.9877296   0.87096795 -0.48450158 -0.21400616]
 [-0.19754592 -0.12971863  0.53295174  0.83656954]]
Kmelia      0.412544
Adam        0.242853
Sofiane     1.196814
Karima     -0.683729
Djamel     -1.061667
hamida     -1.013522
Riadh       1.737362
Lamia      -1.183213
A

In [4]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
from scipy.stats import pearsonr
from sklearn import svm
from sklearn.decomposition import PCA
import statsmodels.formula.api as smf
import seaborn as sns

def plot_circle_corr(x,y):
    
        fig,ax=plt.subplots()
        ax.axhline(y=0,color='k')
        ax.axvline(x=0,color='k')
        theta=np.linspace(0,2*np.pi,100)
        x1=np.cos(theta)
        x2=np.sin(theta)
        ax.plot(x1,x2)
        G1=x.to_numpy().astype(float)
        G2=y.to_numpy().astype(float)
        ax.scatter(G1,G2,s=150,color="k")
        for i in range(len(G1)):
            text.append(x.index[i])
            ax.annotate(text[i],(G1[i],G2[i]),fontsize=13,color='b')

        v=G1.tolist()
        w=G2.tolist()
        for i in range(len(G1)):
            array = np.array([[0, 0, v[i], w[i]], [0, 0, v[i],w[i]]])
            X, Y, V, W = zip(*array)
            ax.quiver(X, Y, V, W, angles='xy', scale_units='xy',color=['r','r'],scale=1)


        ax.grid(linestyle='--')
        ax.show()
        #fin de circle
        return ax.close()
def plot_corrdonne(x,y):
        fig,ax=plt.subplots()
        ax.axhline(y=0,color='k')
        ax.axvline(x=0,color='k')
        ax.grid(True)
        F1_=x.to_numpy()
        F2_=y.to_numpy()
        ax.scatter(F1_,F2_,s=150,color="k")
        for i in range(len(F1)):
            text.append(y.index[i])
            ax.annotate(text[i],(F1_[i],F2_[i]),fontsize=13)
        ax.plot()
        return plt.close()



inertie_relative=[]
indexe=[]

#matrix correlation 


#from sklearn.preprocessing import StandarScaler
dat=pd.read_csv("prb.csv")
for i in dat["Unnamed: 0"]:
    indexe.append(i)
dat=dat.drop("Unnamed: 0",axis=1)
text=[]
x=[]
G1=[]
G2=[]
n=4
m=9
matrix=dat.to_numpy().astype(float)
x=matrix.mean(axis=0)
y=matrix.std(axis=0)
for i in range(m):
    for j in range(n):
        matrix[i][j]=(matrix[i][j]-x[j])/y[j]
tran=(1/m)*np.dot(matrix.T,matrix)
data=pd.DataFrame(matrix,index=indexe,columns=['prv',"add","vitess","logistique de transport"])
print("----------MATRIX OF COR---------")
R=dat.corr()
p=np.linalg.eigvals(R)
inertie_absolue=[p[0],p[1],p[0]+p[1]]
for i in range(len(inertie_absolue)):
    inertie_relative.append(inertie_absolue[i]/n)
#print(inertie_absolue,inertie_relative)
h=np.linalg.eig(R)
b=h[1:2]
def colum(mat,i):
    return [row[i].T for row in mat]
u1=np.array(colum(b,0))
u2=np.array(colum(b,1))
F1=pd.DataFrame(np.dot(matrix,u1.T),index=data.index)
F2=pd.DataFrame(np.dot(matrix,u2.T),index=data.index)
for i in range(4):
    coef_cor,pvalue=pearsonr(matrix[:,i],F1[0])
    G1.append(coef_cor)
    coef_cor,pvalue=pearsonr(matrix[:,i],F2[0])
    G2.append(coef_cor)
G1=pd.DataFrame(G1,index=data.columns)
G2=pd.DataFrame(G2,index=data.columns)
print(dat)


----------MATRIX OF COR---------
   Prévision   ADD   Logistique   Transport
0         6.0   6.0          5.0        5.5
1         8.0   8.0          8.0        8.0
2         6.0   7.0         11.0        9.5
3        14.5  14.5         15.5       15.0
4        14.0  14.0         12.0       12.5
5        11.0  10.5          5.5        7.0
6         5.5   7.0         14.0       11.5
7        13.0  12.5          8.5        9.5
8         9.0   9.5         12.0       12.5


In [5]:
hello= smf.ols(formula = 'prv ~ vitess', data=data).fit()
hello.summary()

/home/khalil/anaconda3/lib/python3.9/site-packages/scipy/stats/stats.py:1541: UserWarning: kurtosistest only valid for n>=20 ... continuing anyway, n=9
  warnings.warn("kurtosistest only valid for n>=20 ... continuing "


<class 'statsmodels.iolib.summary.Summary'>
"""
                            OLS Regression Results                            
==============================================================================
Dep. Variable:                    prv   R-squared:                       0.054
Model:                            OLS   Adj. R-squared:                 -0.081
Method:                 Least Squares   F-statistic:                    0.3986
Date:                Thu, 18 Aug 2022   Prob (F-statistic):              0.548
Time:                        14:59:30   Log-Likelihood:                -12.521
No. Observations:                   9   AIC:                             29.04
Df Residuals:                       7   BIC:                             29.44
Df Model:                           1                                         
Covariance Type:            nonrobust                                         
==============================================================================
                 coef    std err          t      P>|t|      [0.025      0.975]
------------------------------------------------------------------------------
Intercept   1.978e-16      0.368   5.38e-16      1.000      -0.869       0.869
vitess         0.2321      0.368      0.631      0.548      -0.637       1.101
==============================================================================
Omnibus:                        2.648   Durbin-Watson:                   2.290
Prob(Omnibus):                  0.266   Jarque-Bera (JB):                0.891
Skew:                          -0.098   Prob(JB):                        0.641
Kurtosis:                       1.471   Cond. No.                         1.00
==============================================================================

Notes:
[1] Standard Errors assume that the covariance matrix of the errors is correctly specified.
"""